# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=100)),
                ('title_two', models.CharField(max_length=100)),
                ('title_three', models.CharField(max_length=100)),
                ('title_four', models.CharField(max_length=100)),
                ('title_five', models.CharField(max_length=100)),
                ('title_six', models.CharField(max_length=100)),
            ],
        ),
    ]
