# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='updated',
        ),
    ]
